services:

  crm-fastapi-light:
    build:
      dockerfile: ./Dockerfile
    ports:
      - "8000:8000"
    environment:
      - ENVIRONMENT=development
      - POSTGRES_URL=${POSTGRES_URL}
      - SECRET_KEY=${SECRET_KEY}
      - JWT_ALGORITHM=${JWT_ALGORITHM}
      - ACCESS_TOKEN_EXPIRE_MINUTES=${ACCESS_TOKEN_EXPIRE_MINUTES}
    depends_on:
      crm-postgres:
        condition: service_healthy
    volumes:
      - ./src/:/app/src/src
    networks:
      - postgres_network

  crm-postgres:
    image: postgres:17-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASS}
      POSTGRES_DB: ${POSTGRES_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - postgres_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
  
  # pgadmin:
  #   image: dpage/pgadmin4
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: admin@example.com
  #     PGADMIN_DEFAULT_PASSWORD: admin123
  #   ports:
  #     - "8080:80"
  #   depends_on:
  #     - crm-postgres
  #   networks:
  #     - postgres_network
volumes:
  postgres_data:
#   redis_data:

networks:
  postgres_network:
