"""meetings

Revision ID: 4bff2e6e5242
Revises: 72a9fa60c115
Create Date: 2025-05-23 20:47:14.141968

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4bff2e6e5242'
down_revision: Union[str, None] = '72a9fa60c115'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meetings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('start_time', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('duration', sa.Interval(), nullable=False),
    sa.Column('cancelled', sa.Boolean(), nullable=False),
    sa.Column('team_id', sa.UUID(), nullable=False),
    sa.Column('organizer_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['organizer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('meeting_participants',
    sa.Column('participant_id', sa.UUID(), nullable=False),
    sa.Column('meeting_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ),
    sa.ForeignKeyConstraint(['participant_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('participant_id', 'meeting_id')
    )
    op.add_column('tasks', sa.Column('score', sa.Enum('ONE', 'TWO', 'THREE', 'FOUR', 'FIVE', name='taskscore'), nullable=True))
    op.alter_column('tasks', 'author_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('tasks', 'team_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('tasks', 'rating')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('rating', postgresql.ENUM('ONE', 'TWO', 'THREE', 'FOUR', 'FIVE', name='taskscore'), autoincrement=False, nullable=True))
    op.alter_column('tasks', 'team_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('tasks', 'author_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_column('tasks', 'score')
    op.drop_table('meeting_participants')
    op.drop_table('meetings')
    # ### end Alembic commands ###
