"""cascade

Revision ID: e3ef630d75ed
Revises: 4bff2e6e5242
Create Date: 2025-05-28 15:03:39.315335

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e3ef630d75ed'
down_revision: Union[str, None] = '4bff2e6e5242'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('task_comments_task_id_fkey', 'task_comments', type_='foreignkey')
    op.drop_constraint('task_comments_author_id_fkey', 'task_comments', type_='foreignkey')
    op.create_foreign_key(None, 'task_comments', 'tasks', ['task_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'task_comments', 'users', ['author_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'task_comments', type_='foreignkey')
    op.drop_constraint(None, 'task_comments', type_='foreignkey')
    op.create_foreign_key('task_comments_author_id_fkey', 'task_comments', 'users', ['author_id'], ['id'])
    op.create_foreign_key('task_comments_task_id_fkey', 'task_comments', 'tasks', ['task_id'], ['id'])
    # ### end Alembic commands ###
